/* Product catalogue data
   Each product supports: id, name, cat, catLabel, images[], description,
   availability: 'ready' | 'mto'  (ready = dispatch/stock, mto = made to order)
   Optional: modelScale, model, modelRotation
*/
const PRODUCTS = [
  { id:'SBNG1030085', name:'Aurora Gemstone Bangle', cat:'bangle', catLabel:'Bangle', availability:'ready',
    collections:['everyday-luxury','royal-heritage'],
    images:['SBNG1030085_hero','SBNG1030085_1','SBNG1030085_2','SBNG1030085_3'],
    description:'Intricately designed bangles studded with multi-coloured gemstones, representing auspiciousness and vibrant tradition.' },
  { id:'SHAR1012267', name:'Uncut Diamond Polki Pendant Chain', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['royal-heritage','diamond-collection','bridal-elegance'],
    images:['SHAR1012267_hero','SHAR1012267_1','SHAR1012267_2','SHAR1012267_3'],
    description:'An intricately crafted polki pendant with uncut diamonds and emerald drops, reflecting timeless heritage.' },
  { id:'SPND998476', name:'Lakshmi Elephant Temple Pendant', cat:'necklace', catLabel:'Necklace', availability:'ready',
    collections:['temple-jewellery','bridal-elegance','royal-heritage'],
    images:['SPND998476_hero','SPND998476_1','SPND998476_2','SPND998476_3'],
    modelScale: 1,
    description:'An exquisite temple necklace showcasing Goddess Lakshmi, surrounded by intricate elephant motifs, green beads and pearls.' },
  { id:'SPND982328', name:'Lakshmi Peacock Temple Pendant', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['temple-jewellery','bridal-elegance'],
    images:['SPND982328_1'],
    description:'A regal temple pendant with twin peacocks and Goddess Lakshmi at its heart, finished with emerald and pearl drops.' },
  { id:'SJMK741494', name:'Lakshmi Ruby Jhumka Earrings', cat:'earring', catLabel:'Earrings', availability:'ready',
    collections:['temple-jewellery','bridal-elegance'],
    images:['SJMK741494_hero'],
    description:'Gold Lakshmi temple earrings with ruby accents, blending tradition with timeless elegance.' },
  { id:'SERN1037986', name:'Peacock Ruby Stud Earrings', cat:'earring', catLabel:'Earrings', availability:'ready',
    collections:['everyday-luxury','diamond-collection'],
    images:['SERN1037986_hero'],
    description:'Gold studs featuring peacock motifs, embellished with ruby accents that symbolise beauty and grace.' },
  { id:'SERN1052778', name:'Lakshmi Emerald Sunburst Studs', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['antique-collection','temple-jewellery'],
    images:['SERN1052778_hero'],
    description:'Antique-finish studs featuring Goddess Lakshmi, enhanced with emerald and pearl drops for divine elegance.' },
  { id:'SNEC979916', name:'Emerald Lakshmi Temple Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['temple-jewellery','bridal-elegance','royal-heritage'],
    images:['SNEC979916_hero'],
    description:'A grand temple necklace featuring a prominent goddess motif, accented with green stones and pearl drops.' },
  { id:'SRNG1043042', name:'Sacred Deity Ruby Ring', cat:'ring', catLabel:'Ring', availability:'ready',
    collections:['temple-jewellery','royal-heritage'],
    images:['SRNG1043042_hero'],
    description:'A finely detailed gold ring featuring a sacred deity motif, accented with vibrant rubies that enhance its spiritual charm.' },
  { id:'SHAR1013484', name:'Emerald Strand Lakshmi Pendant', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['temple-jewellery','bridal-elegance'],
    images:['SHAR1013484_hero'],
    description:'Multiple strands of green beads come together with a detailed temple pendant, showcasing divine artistry.' },
  { id:'SJMK1044538', name:'Ruby Emerald Temple Jhumkas', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['temple-jewellery','bridal-elegance'],
    images:['SJMK1044538_hero'],
    description:'Temple-inspired jhumkas featuring ruby and emerald accents, finished with cascading pearls for a classic touch.' },

  /* ——— Sweet 16 Collection (from PDF) ——— */
  { id:'SBRC887806', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC887806_model','SBRC887806_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.30 ct diamonds (GH VS).',
    purity:'18 KT', gross:'5.80 g', netGold:'5.80 g', diamond:'0.30 ct', stones:'Diamond GH VS', price:'$1,720' },
  { id:'SRNG920359', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG920359_model','SRNG920359_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.30 ct diamonds and 0.20 ct accent stones.',
    purity:'18 KT', gross:'2.64 g', netGold:'2.64 g', diamond:'0.30 ct', stones:'0.20 ct', price:'$940' },
  { id:'SPST909296', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST909296_model','SPST909296_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.42 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.286 g', netGold:'3.286 g', diamond:'0.42 ct', stones:'Diamond GH VS', price:'$1,330' },
  { id:'SMAT909342', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT909342_model','SMAT909342_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.74 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.032 g', netGold:'3.032 g', diamond:'0.74 ct', stones:'Diamond GH VS', price:'$1,680' },
  { id:'SERN895430', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN895430_model','SERN895430_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.25 ct diamonds (GH VS).',
    purity:'18 KT', gross:'5.79 g', netGold:'5.79 g', diamond:'0.25 ct', stones:'Diamond GH VS', price:'$1,550' },
  { id:'NBRC901545', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['NBRC901545_model','NBRC901545_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.94 ct diamonds (GH VS).',
    purity:'18 KT', gross:'8.81 g', netGold:'8.81 g', diamond:'0.94 ct', stones:'Diamond GH VS', price:'$3,160' },
  { id:'SERN931794', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN931794_model','SERN931794_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.49 ct diamonds and 1.19 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.905 g', netGold:'2.905 g', diamond:'0.49 ct', stones:'1.19 ct', price:'$1,390' },
  { id:'SMAT932512', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT932512_model','SMAT932512_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.22 ct diamonds and 1.38 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.538 g', netGold:'2.538 g', diamond:'0.22 ct', stones:'1.38 ct', price:'$900' },
  { id:'SPST932513', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST932513_model','SPST932513_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.22 ct diamonds and 1.38 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.538 g', netGold:'2.538 g', diamond:'0.22 ct', stones:'1.38 ct', price:'$900' },
  { id:'SBRC926223', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC926223_model','SBRC926223_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.22 ct diamonds and 1.38 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.538 g', netGold:'2.538 g', diamond:'0.22 ct', stones:'1.38 ct', price:'$900' },
  { id:'SRNG900970', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG900970_model','SRNG900970_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.52 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.39 g', netGold:'3.39 g', diamond:'0.52 ct', stones:'Diamond GH VS', price:'$1,500' },
  { id:'SRNG935277', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG935277_model','SRNG935277_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.10 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.10 g', netGold:'1.10 g', diamond:'0.10 ct', stones:'Diamond GH VS', price:'$360' },
  { id:'SRNG967440', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG967440_model','SRNG967440_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.24 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.971 g', netGold:'1.971 g', diamond:'0.24 ct', stones:'Diamond GH VS', price:'$750' },
  { id:'SNEC951544', name:'Sweet 16 Diamond Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['sweet-16'],
    images:['SNEC951544_model','SNEC951544_product'],
    description:'Sweet 16 Collection — necklace in 18 KT gold with 0.93 ct diamonds.',
    purity:'18 KT', gross:'5.584 g', netGold:'5.584 g', diamond:'0.93 ct', stones:'Diamond', price:'$2,240' },
  { id:'SERN933646', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN933646_model','SERN933646_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.42 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.896 g', netGold:'3.896 g', diamond:'0.42 ct', stones:'Diamond GH VS', price:'$1,330' },
  { id:'SBRC878178', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC878178_model','SBRC878178_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.51 ct diamonds (GH VS).',
    purity:'18 KT', gross:'4.248 g', netGold:'4.248 g', diamond:'0.51 ct', stones:'Diamond GH VS', price:'$1,500' },
  { id:'SERN936326', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN936326_model','SERN936326_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.33 ct diamonds and 0.67 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.906 g', netGold:'2.906 g', diamond:'0.33 ct', stones:'0.67 ct', price:'$1,060' },
  { id:'SBRC951194', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC951194_model','SBRC951194_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold.',
    purity:'18 KT', gross:'—', netGold:'—', diamond:'—', stones:'Diamond', price:'Price on request' },
  { id:'SNEC939957', name:'Sweet 16 Diamond Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['sweet-16'],
    images:['SNEC939957_model','SNEC939957_product'],
    description:'Sweet 16 Collection — necklace in 18 KT gold with 0.34 ct diamonds.',
    purity:'18 KT', gross:'2.872 g', netGold:'2.872 g', diamond:'0.34 ct', stones:'Diamond', price:'$1,010' },
  { id:'SBRC887805', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC887805_model','SBRC887805_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.39 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.84 g', netGold:'3.84 g', diamond:'0.39 ct', stones:'Diamond GH VS', price:'$1,400' },
  { id:'SRNG928656', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG928656_model','SRNG928656_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 1.16 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.908 g', netGold:'3.908 g', diamond:'1.16 ct', stones:'Diamond GH VS', price:'$2,870' },
  { id:'SPST911141', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST911141_model','SPST911141_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.12 ct diamonds and 0.4 ct accent stones (GH VS).',
    purity:'18 KT', gross:'1.166 g', netGold:'1.166 g', diamond:'0.12 ct', stones:'0.4 ct', price:'$420' },
  { id:'SMAT911178', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT911178_model','SMAT911178_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.2 ct diamonds and 0.4 ct accent stones (GH VS).',
    purity:'18 KT', gross:'2.37 g', netGold:'2.37 g', diamond:'0.2 ct', stones:'0.4 ct', price:'$780' },
  { id:'SERN935620', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN935620_model','SERN935620_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.56 ct diamonds (GH VS).',
    purity:'18 KT', gross:'2.348 g', netGold:'2.348 g', diamond:'0.56 ct', stones:'Diamond GH VS', price:'$1,290' },
  { id:'SERN948867', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN948867_model','SERN948867_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.38 ct diamonds.',
    purity:'18 KT', gross:'2.874 g', netGold:'2.874 g', diamond:'0.38 ct', stones:'Diamond', price:'$1,060' },
  { id:'SBRC938633', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC938633_model','SBRC938633_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.59 ct diamonds (GH VS).',
    purity:'18 KT', gross:'6.074 g', netGold:'6.074 g', diamond:'0.59 ct', stones:'Diamond GH VS', price:'$2,150' },
  { id:'SNEC917387', name:'Sweet 16 Diamond Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['sweet-16'],
    images:['SNEC917387_model','SNEC917387_product'],
    description:'Sweet 16 Collection — necklace in 18 KT gold with 5.71 ct diamonds (EF VVS).',
    purity:'18 KT', gross:'12.958 g', netGold:'12.958 g', diamond:'5.71 ct', stones:'Diamond EF VVS', price:'$12,520' },
  { id:'SERN951053', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN951053_model','SERN951053_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 0.79 ct diamonds (EF VVS).',
    purity:'18 KT', gross:'1.931 g', netGold:'1.931 g', diamond:'0.79 ct', stones:'Diamond EF VVS', price:'$2,160' },
  { id:'SERN961550', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN961550_model','SERN961550_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 1.85 ct diamonds (GH VS).',
    purity:'18 KT', gross:'6.749 g', netGold:'6.749 g', diamond:'1.85 ct', stones:'Diamond GH VS', price:'$4,110' },
  { id:'SBRC868995', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC868995_model','SBRC868995_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.18 ct diamonds (GH VS).',
    purity:'18 KT', gross:'2.337 g', netGold:'2.337 g', diamond:'0.18 ct', stones:'Diamond GH VS', price:'$710' },
  { id:'SBRC939773', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC939773_model','SBRC939773_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.34 ct diamonds (GH VS).',
    purity:'18 KT', gross:'2.592 g', netGold:'2.592 g', diamond:'0.34 ct', stones:'Diamond GH VS', price:'$950' },
  { id:'SERN917197', name:'Sweet 16 Diamond Earrings', cat:'earring', catLabel:'Earrings', availability:'mto',
    collections:['sweet-16'],
    images:['SERN917197_model','SERN917197_product'],
    description:'Sweet 16 Collection — earrings in 18 KT gold with 1.01 ct diamonds (GH VS).',
    purity:'18 KT', gross:'4.768 g', netGold:'4.768 g', diamond:'1.01 ct', stones:'Diamond GH VS', price:'$2,540' },
  { id:'SPST8794513', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST8794513_model','SPST8794513_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.79 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.812 g', netGold:'3.812 g', diamond:'0.79 ct', stones:'Diamond GH VS', price:'$1,830' },
  { id:'SMAT879452', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT879452_model','SMAT879452_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.79 ct diamonds (GH VS).',
    purity:'18 KT', gross:'3.812 g', netGold:'3.812 g', diamond:'0.79 ct', stones:'Diamond GH VS', price:'$1,830' },
  { id:'SNEC935558', name:'Sweet 16 Diamond Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['sweet-16'],
    images:['SNEC935558_model','SNEC935558_product'],
    description:'Sweet 16 Collection — necklace in 18 KT gold with 0.36 ct diamonds (GH VS).',
    purity:'18 KT', gross:'5.098 g', netGold:'5.098 g', diamond:'0.36 ct', stones:'Diamond GH VS', price:'$1,480' },
  { id:'SBRC862323', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC862323_model','SBRC862323_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.92 ct diamonds (GH VS).',
    purity:'18 KT', gross:'7.37 g', netGold:'7.37 g', diamond:'0.92 ct', stones:'Diamond GH VS', price:'$2,950' },
  { id:'SMAT935557', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT935557_model','SMAT935557_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.29 ct diamonds (GH VS).',
    purity:'18 KT', gross:'2.922 g', netGold:'2.922 g', diamond:'0.29 ct', stones:'Diamond GH VS', price:'$1000' },
  { id:'SNEC939967', name:'Sweet 16 Diamond Necklace', cat:'necklace', catLabel:'Necklace', availability:'mto',
    collections:['sweet-16'],
    images:['SNEC939967_model','SNEC939967_product'],
    description:'Sweet 16 Collection — necklace in 18 KT gold with 0.73 ct diamonds and 2.96 ct accent stones.',
    purity:'18 KT', gross:'8.68 g', netGold:'8.68 g', diamond:'0.73 ct', stones:'2.96 ct', price:'$2,860' },
  { id:'SMAT9442891', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT9442891_model','SMAT9442891_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.59 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.782 g', netGold:'1.782 g', diamond:'0.59 ct', stones:'Diamond GH VS', price:'$1,230' },
  { id:'SPST944291', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST944291_model','SPST944291_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.59 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.782 g', netGold:'1.782 g', diamond:'0.59 ct', stones:'Diamond GH VS', price:'$1,230' },
  { id:'SMAT924824', name:'Sweet 16 Diamond Mangalsutra', cat:'mangalsutra', catLabel:'Mangalsutra', availability:'mto',
    collections:['sweet-16'],
    images:['SMAT924824_model','SMAT924824_product'],
    description:'Sweet 16 Collection — mangalsutra in 18 KT gold with 0.47 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.426 g', netGold:'1.426 g', diamond:'0.47 ct', stones:'Diamond GH VS', price:'$950' },
  { id:'SPST924827', name:'Sweet 16 Diamond Pendant', cat:'pendant', catLabel:'Pendant', availability:'mto',
    collections:['sweet-16'],
    images:['SPST924827_model','SPST924827_product'],
    description:'Sweet 16 Collection — pendant in 18 KT gold with 0.37 ct diamonds (GH VS).',
    purity:'18 KT', gross:'1.026 g', netGold:'1.026 g', diamond:'0.37 ct', stones:'Diamond GH VS', price:'$900' },
  { id:'SBRC884457', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC884457_model','SBRC884457_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 0.23 ct diamonds (EF VVS).',
    purity:'18 KT', gross:'1.55 g', netGold:'1.55 g', diamond:'0.23 ct', stones:'Diamond EF VVS', price:'$900' },
  { id:'SRNG951197', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG951197_model','SRNG951197_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.23 ct diamonds (EF VVS).',
    purity:'18 KT', gross:'1.55 g', netGold:'1.55 g', diamond:'0.23 ct', stones:'Diamond EF VVS', price:'$900' },
  { id:'SBRC782666', name:'Sweet 16 Diamond Bracelet', cat:'bracelet', catLabel:'Bracelet', availability:'mto',
    collections:['sweet-16'],
    images:['SBRC782666_model','SBRC782666_product'],
    description:'Sweet 16 Collection — bracelet in 18 KT gold with 1.38 ct diamonds (GH VS).',
    purity:'18 KT', gross:'6.244 g', netGold:'6.244 g', diamond:'1.38 ct', stones:'Diamond GH VS', price:'$2,990' },
  { id:'SRNG924006', name:'Sweet 16 Diamond Ring', cat:'ring', catLabel:'Ring', availability:'mto',
    collections:['sweet-16'],
    images:['SRNG924006_model','SRNG924006_product'],
    description:'Sweet 16 Collection — ring in 18 KT gold with 0.47 ct diamonds (GH VS).',
    purity:'18 KT', gross:'4.40 g', netGold:'4.40 g', diamond:'0.47 ct', stones:'Diamond GH VS', price:'$1,600' },
];

/** Live catalogue — base products + admin uploads (pmj_catalogue_products in localStorage) */
function getCatalogueProducts() {
  let adminProducts = [];
  try {
    const raw = localStorage.getItem('pmj_catalogue_products');
    if (raw) adminProducts = JSON.parse(raw);
  } catch (e) { /* ignore */ }

  const byId = new Map();
  PRODUCTS.forEach((p) => byId.set(p.id, { ...p }));
  if (Array.isArray(adminProducts)) {
    adminProducts.forEach((p) => {
      if (p?.id) byId.set(p.id, { ...byId.get(p.id), ...p });
    });
  }
  return [...byId.values()];
}

window.getCatalogueProducts = getCatalogueProducts;

const SPEC_DEFAULTS = {
  purity: 'Add purity',
  gross: 'Add gross weight',
  netGold: 'Add net gold weight',
  diamond: 'Add diamond / stone weight',
  stones: 'Add stone details',
  price: 'Price on request'
};

